* Description
  This is a Jabber/Gtalk bot written using the python-jabberbot
  library.  This bot is written to behave like a chatroom, where all
  the messages are sent to all the subscribed users.

* Usage

  + Depends: python-jabberbot, xmpppy

  + You are required to have a file settings.py with the variables, JID,
    PASSWORD, CHANNEL, RES

  + To add new users, the admin can either add them manually to a USERS
    dict in a state.py file, or they can be invited and then added.

* Bugs/Issues

  + *Known Issue*: Google doesn't allow sending and receiving more than
    50 messages in a period of 12.5 seconds.  This is a big problem if
    you have even three or four members in the channel.  Use jabber.org
    for hosting the bot, instead. 

  + Report other bugs/issues at [[https://github.com/punchagan/childrens-park/issues][GitHub]]

* TO-DO/Ideas
  1. Private Messaging
     For instance, @ringo blah blah, should be shown only to ringo,
     nobody else. 

  2. Translation
     te2hi or te2en bot for translation help

  3. Reminders 
     For instance -- ,setreminder 2011/04/15 20:00 Priya's
     Treat This should keep reminding at pre-set intervals before the
     event.

  4. Score bot
     We should be able to keep track of scores for various objects,
     using object-name++ and object-name--

  5. Replace regex
     s/old_word/new_word should do the replacements
